name: Check

on: 
  push:

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if required files exist or not
        id: check_files
        run: |
          missing_files=()
          [ ! -f tk.py ] && missing_files+=("tk.py")
          [ ! -f README.md ] && missing_files+=("README.md")
          [ ! -f tkforge.py ] && missing_files+=("tkforge.py")
          [ ! -f gui.py ] && missing_files+=("gui.py")
          [ ! -f CONTRIBUTING.md ] && missing_files+=("CONTRIBUTING.md")
          [ ! -f requirements.txt ] && missing_files+=("requirements.txt")
          [ ! -f CODE_OF_CONDUCT.md ] && missing_files+=("CODE_OF_CONDUCT.md")

          if [ ${#missing_files[@]} -ne 0 ]; then
            echo "❌ Missing files: ${missing_files[@]}"
            exit 1
          else
            echo "✅ All required files exist."
          fi